// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxs7rl0SbqPr3JhycIObVJmRkJfxsuK_U',
    appId: '1:576307212775:web:76fc6707ef5a4fa88c4d42',
    messagingSenderId: '576307212775',
    projectId: 'fingerprintmis8',
    authDomain: 'fingerprintmis8.firebaseapp.com',
    storageBucket: 'fingerprintmis8.firebasestorage.app',
    measurementId: 'G-P3CGLM8Y64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqAuHf1vK6-08m91-WNkYGOsmdbkZFsfs',
    appId: '1:576307212775:android:00a9c0aaa18df0aa8c4d42',
    messagingSenderId: '576307212775',
    projectId: 'fingerprintmis8',
    storageBucket: 'fingerprintmis8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVk25T9Ya_qP1NOvSbOehLwix5ztuyNMo',
    appId: '1:576307212775:ios:40ea704d927b4ae78c4d42',
    messagingSenderId: '576307212775',
    projectId: 'fingerprintmis8',
    storageBucket: 'fingerprintmis8.firebasestorage.app',
    iosBundleId: 'com.example.fingerprintmis8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVk25T9Ya_qP1NOvSbOehLwix5ztuyNMo',
    appId: '1:576307212775:ios:40ea704d927b4ae78c4d42',
    messagingSenderId: '576307212775',
    projectId: 'fingerprintmis8',
    storageBucket: 'fingerprintmis8.firebasestorage.app',
    iosBundleId: 'com.example.fingerprintmis8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxs7rl0SbqPr3JhycIObVJmRkJfxsuK_U',
    appId: '1:576307212775:web:030ff1d98bf6e91b8c4d42',
    messagingSenderId: '576307212775',
    projectId: 'fingerprintmis8',
    authDomain: 'fingerprintmis8.firebaseapp.com',
    storageBucket: 'fingerprintmis8.firebasestorage.app',
    measurementId: 'G-3KEYN9WV8E',
  );
}
